version: '3.8'

services:
  telegram-bot:
    container_name: 'Bot-Cotacao'
    image: cotacaoatualbot:v1.1.0
    environment:
      TOKEN_BOT: ${TOKEN_BOT}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile