version: '3.8'

services:
  telegram-bot:
    container_name: 'Bot-Cotacao'
    image: <IMAGEM MAIS ATUAL PARA CONTAIENER>
    environment:
      TOKEN_BOT: ${TOKEN_BOT}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile